### ISSUE TITLE
Error during make

### ISSUE THREAD

**Issue by aziele** [EvolBioInf/phylonium#1]
Hi, 

I got the following error during `make`:

```
evo_model.cxx: In function ‘size_t intr(const char*, const char*, size_t)’:
evo_model.cxx:129:46: error: ‘_mm_shuffle_epi8’ was not declared in this scope
   __m128i reversed = _mm_shuffle_epi8(o, mask);
make[1]: *** [phylonium-evo_model.o] Error 1
```

Any ideas what could be wrong?

**Comment by kloetzl** [comment]
Do you know what level of vector instructions is supported by your CPU? On Linux you can check via `cat /proc/cpuinfo| grep flags | head -n 1`. I am specifically interested in SSSE3

**Comment by aziele** [comment]
Thanks for the command. I got the following flags:

`flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm ida arat epb xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid`

**Comment by kloetzl** [comment]
I pushed a commit that should fix the issue. Would you care to verify and close this issue if it works?

**Comment by aziele** [comment]
Your commit fixed the issue. Everything works great. Thank you!

**Comment by kloetzl** [comment]
> Everything works great.

Well, phylonium is significantly faster on CPUs that support AVX2. I should also implement a fast substitution count for machines with only SSE2.

See #2.
