### ISSUE TITLE
Filename that contain point will be cut in the output

### ISSUE THREAD

**Issue by chen1i6c04** [EvolBioInf/phylonium#5]
Hi 
I try to use ```phylonium``` and in the output, filename will be cut if contain point.
example ```R21.0001 → R21```
Could you fix it？
Thanks

**Comment by kloetzl** [comment]
Hi,
Thanks for using phylonium. The idea behind this behaviour is that if the input is `NA2187.fasta` then the `.fasta` is irrelevant and only the filename without the extension is printed. I can see how this conflicts with your naming scheme. I'll see what I can do. As a work around you could replace the dot in your filenames with a `_` or similar.

**Comment by kloetzl** [comment]
I created a new commit that strips only known file extensions. Could you give that a try? Let me know if you need help compiling.

**Comment by chen1i6c04** [comment]
The new commit fix my issue, thanks

**Comment by kloetzl** [comment]
Cool, thanks for letting me know.
