### ISSUE TITLE
Defining the total number of substitutions

### ISSUE THREAD

**Issue by goodolgab** [EvolBioInf/phylonium#9]
Hi!

I'm currently working on a dataset of 1000+ _E. coli_ genomes.
Is there a way to find out the number of total sites used by Phylonium when it estimates the number of substitutions per site?

Thanks!

**Comment by kloetzl** [comment]
Apologies, I was on vacation. There is a the option `-p` that will list the segregating sites. Alternatively you can use `-v` to get the coverage which when multiplied with the length and mutation rate with give you the absolute number of mutations. Hope this helps.

**Comment by goodolgab** [comment]
No worries!
And thanks for the reply! Just to clarify, when you mention length, do you mean the branch lengths (i.e. estimated no. of substitutions), or the length of the reference genome?

**Comment by kloetzl** [comment]
I'm thinking along this line: `genome length * portion covered * substitution rate = number of substitutions`.

**Comment by goodolgab** [comment]
This makes a lot of sense! Thank you!
